### ISSUE TITLE
Create /registration RESTful endpoint

### ISSUE THREAD

**Issue by andreytrubin** [andreytrubin/gorkypark#2]
1. Create JSON test files for existing and non-existing users
2. Print out the JSON in response if user registration succeeded
3. Return 400 bad request in case if:
   - User already exists
   - No data for user posted

**Comment by AYasenov** [comment]
Created 2 test JSON files in catalogue test for existing and non existing users. If user doesn't exist registration succeeded, if does or no data for user posted - registration refused.

**Comment by AYasenov** [comment]
Created 2 test JSON files in catalogue test for existing and non existing users. If user doesn't exist registration succeeded, if does or no data for user posted - registration refused.
